# This is a basic workflow to help you get started with the Run Jtest action.
name: Publish Jtest Report

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    # the name of the job
    name: Publish Jtest Report
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # Specifies the type of runner that the job will run on. eg: ubuntu-latest, windows-latest
    runs-on: self-hosted
  
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      
      # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Jtest Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'reports/unit/Jtest_report-xml-junit.xml'
